"""
test_codegen_output_validator.py — v2.7 Phase B coverage for
verify-codegen-output.

Pins:
1. PASS — well-formed spec hits every check.
2. BLOCK — missing `// AUTO-GENERATED` header.
3. BLOCK — missing one helper from imports.
4. BLOCK — raw page.locator( in test body.
5. BLOCK — test count drifts from interactive_controls YAML.
6. BLOCK — waitForLoadState('networkidle') in body.
7. WARN  — page.evaluate( in body, exit 0.
8. BLOCK — ROUTE constant mismatches --route arg.
9. BLOCK — expectAssertion uses an expr outside the 5 DSL forms.
10. BLOCK — file basename mismatches goal_id slug.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPT = (
    REPO_ROOT / ".claude" / "scripts" / "validators" / "verify-codegen-output.py"
)


# ---------------------------------------------------------------------------
# Fixtures + helpers
# ---------------------------------------------------------------------------


GOAL_ID = "G-CAMPAIGN-LIST"
ROUTE = "/admin/campaigns"
SLUG = GOAL_ID.lower()
SPEC_BASENAME = f"{SLUG}.url-state.spec.ts"

YAML_FULL = """\
interactive_controls:
  url_sync: true
  filters:
    - name: status
      values: [draft, active]
      param: status
      assertion: "rows[*].status === param"
  sort:
    - name: created_at
      directions: [asc, desc]
      param: sort
      assertion: "rows monotonically ordered by created_at"
  pagination:
    type: page-number
    page_param: page
    size_param: pageSize
    default_size: 25
    assertion: "rows.length <= 25"
  search:
    name: q
    debounce_ms: 300
    param: q
    assertion: "rows[*].name.includes(param)"
"""


# Expected test count for YAML_FULL:
#   filter status: 2 values + 1 reload = 3
#   sort created_at: 2 directions = 2
#   pagination: 1
#   search: 1
#   total = 7
EXPECTED_N = 7


WELL_FORMED_SPEC = """\
// AUTO-GENERATED by /vg:test step 5d_codegen — DO NOT EDIT BY HAND.
// Source: TEST-GOALS.md goal G-CAMPAIGN-LIST interactive_controls block

import { test, expect } from '@playwright/test';
import {
  applyFilter, applySort, applyPagination, applySearch,
  readUrlParams, readVisibleRows, expectAssertion,
} from '../helpers/interactive';

const ROUTE = '/admin/campaigns';
const ROLE  = 'admin';

test.describe('G-CAMPAIGN-LIST', () => {
  test('filter status=draft syncs', async ({ page }) => {
    await applyFilter(page, 'status', 'draft');
    expect(readUrlParams(page).status).toBe('draft');
    const rows = await readVisibleRows(page);
    await expectAssertion(rows, 'rows[*].status === param', { param: 'draft' });
  });

  test('filter status=active syncs', async ({ page }) => {
    await applyFilter(page, 'status', 'active');
    expect(readUrlParams(page).status).toBe('active');
    const rows = await readVisibleRows(page);
    await expectAssertion(rows, 'rows[*].status === param', { param: 'active' });
  });

  test('filter status reload-persists', async ({ page }) => {
    await page.goto(`${ROUTE}?status=active`);
    await page.reload();
    expect(readUrlParams(page).status).toBe('active');
    const rows = await readVisibleRows(page);
    await expectAssertion(rows, 'rows[*].status === param', { param: 'active' });
  });

  test('sort created_at asc', async ({ page }) => {
    await applySort(page, 'created_at', 'asc');
    const rows = await readVisibleRows(page);
    await expectAssertion(rows, 'rows monotonically ordered by created_at', { dir: 'asc' });
  });

  test('sort created_at desc', async ({ page }) => {
    await applySort(page, 'created_at', 'desc');
    const rows = await readVisibleRows(page);
    await expectAssertion(rows, 'rows monotonically ordered by created_at', { dir: 'desc' });
  });

  test('pagination page-number', async ({ page }) => {
    await applyPagination(page, { page: 2, pageSize: 25 });
    const rows = await readVisibleRows(page);
    await expectAssertion(rows, 'rows.length <= 25', {});
  });

  test('search q debounces', async ({ page }) => {
    await applySearch(page, 'q', 'sale');
    await page.waitForTimeout(350);
    const rows = await readVisibleRows(page);
    await expectAssertion(rows, 'rows[*].name.includes(param)', { param: 'sale' });
  });
});
"""


def _setup_fake_repo(
    tmp_path: Path,
    *,
    spec_text: str,
    spec_basename: str = SPEC_BASENAME,
    yaml_text: str = YAML_FULL,
) -> tuple[Path, Path, Path]:
    """Mirror validator + helpers + write a spec + YAML.

    Returns (repo_root, spec_path, yaml_path).
    """
    scripts_dir = tmp_path / ".claude" / "scripts" / "validators"
    scripts_dir.mkdir(parents=True)
    shutil.copy(SCRIPT, scripts_dir / SCRIPT.name)
    for helper in ("_common.py", "_i18n.py", "_repo_root.py"):
        src = REPO_ROOT / ".claude" / "scripts" / "validators" / helper
        if src.exists():
            shutil.copy(src, scripts_dir / helper)

    out_dir = tmp_path / "generated"
    out_dir.mkdir()
    spec_path = out_dir / spec_basename
    spec_path.write_text(spec_text, encoding="utf-8")

    yaml_path = tmp_path / "controls.yaml"
    yaml_path.write_text(yaml_text, encoding="utf-8")
    return tmp_path, spec_path, yaml_path


def _run(
    repo: Path,
    spec_path: Path,
    yaml_path: Path,
    *,
    goal_id: str = GOAL_ID,
    route: str = ROUTE,
) -> tuple[int, dict]:
    env = os.environ.copy()
    env["VG_REPO_ROOT"] = str(repo)
    proc = subprocess.run(
        [
            sys.executable,
            str(repo / ".claude" / "scripts" / "validators" / SCRIPT.name),
            "--spec-path", str(spec_path),
            "--goal-id", goal_id,
            "--route", route,
            "--interactive-controls-yaml", str(yaml_path),
        ],
        capture_output=True, text=True, cwd=repo, env=env, timeout=15,
    )
    try:
        data = json.loads(proc.stdout.strip().splitlines()[-1])
    except (json.JSONDecodeError, IndexError):
        data = {
            "verdict": "ERROR",
            "raw_stdout": proc.stdout,
            "raw_stderr": proc.stderr,
        }
    return proc.returncode, data


@pytest.fixture(autouse=True)
def _cleanup_vg_repo_root_env():
    original = os.environ.get("VG_REPO_ROOT")
    yield
    if original is None:
        os.environ.pop("VG_REPO_ROOT", None)
    else:
        os.environ["VG_REPO_ROOT"] = original


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def test_pass_well_formed_spec(tmp_path):
    repo, spec, yaml_p = _setup_fake_repo(
        tmp_path, spec_text=WELL_FORMED_SPEC,
    )
    rc, data = _run(repo, spec, yaml_p)
    assert rc == 0, data
    assert data["verdict"] == "PASS", data


def test_block_on_missing_auto_generated_header(tmp_path):
    bad = WELL_FORMED_SPEC.replace(
        "// AUTO-GENERATED by /vg:test step 5d_codegen — DO NOT EDIT BY HAND.\n",
        "// hand-written\n",
    )
    repo, spec, yaml_p = _setup_fake_repo(tmp_path, spec_text=bad)
    rc, data = _run(repo, spec, yaml_p)
    assert rc == 1, data
    assert data["verdict"] == "BLOCK", data
    assert any(
        e["type"] == "codegen_missing_auto_generated_header"
        for e in data["evidence"]
    )


def test_block_on_missing_helper_imports(tmp_path):
    # Drop applySort from imports.
    bad = WELL_FORMED_SPEC.replace("applySort, ", "")
    repo, spec, yaml_p = _setup_fake_repo(tmp_path, spec_text=bad)
    rc, data = _run(repo, spec, yaml_p)
    assert rc == 1, data
    assert data["verdict"] == "BLOCK", data
    assert any(
        e["type"] == "codegen_missing_helper_import"
        for e in data["evidence"]
    )


def test_block_on_raw_locator_outside_imports(tmp_path):
    bad = WELL_FORMED_SPEC.replace(
        "    await applyFilter(page, 'status', 'draft');",
        "    await page.locator('[data-testid=\"filter-status\"]').click();",
    )
    repo, spec, yaml_p = _setup_fake_repo(tmp_path, spec_text=bad)
    rc, data = _run(repo, spec, yaml_p)
    assert rc == 1, data
    assert data["verdict"] == "BLOCK", data
    assert any(
        e["type"] == "codegen_raw_locator_in_body"
        for e in data["evidence"]
    )


def test_block_on_test_count_mismatch(tmp_path):
    # Drop one test() block — count goes from 7 to 6.
    bad = WELL_FORMED_SPEC.replace(
        "  test('search q debounces', async ({ page }) => {\n"
        "    await applySearch(page, 'q', 'sale');\n"
        "    await page.waitForTimeout(350);\n"
        "    const rows = await readVisibleRows(page);\n"
        "    await expectAssertion(rows, 'rows[*].name.includes(param)', { param: 'sale' });\n"
        "  });\n",
        "",
    )
    repo, spec, yaml_p = _setup_fake_repo(tmp_path, spec_text=bad)
    rc, data = _run(repo, spec, yaml_p)
    assert rc == 1, data
    assert data["verdict"] == "BLOCK", data
    types = [e["type"] for e in data["evidence"]]
    assert "codegen_test_count_mismatch" in types, data


def test_block_on_networkidle(tmp_path):
    bad = WELL_FORMED_SPEC.replace(
        "    await page.waitForTimeout(350);",
        "    await page.waitForLoadState('networkidle');",
    )
    repo, spec, yaml_p = _setup_fake_repo(tmp_path, spec_text=bad)
    rc, data = _run(repo, spec, yaml_p)
    assert rc == 1, data
    assert data["verdict"] == "BLOCK", data
    assert any(
        e["type"] == "codegen_networkidle_forbidden"
        for e in data["evidence"]
    )


def test_warn_on_page_evaluate(tmp_path):
    bad = WELL_FORMED_SPEC.replace(
        "    const rows = await readVisibleRows(page);\n"
        "    await expectAssertion(rows, 'rows[*].name.includes(param)', { param: 'sale' });",
        "    const errs = await page.evaluate(() => window.__errs || []);\n"
        "    expect(errs.length).toBe(0);\n"
        "    const rows = await readVisibleRows(page);\n"
        "    await expectAssertion(rows, 'rows[*].name.includes(param)', { param: 'sale' });",
    )
    repo, spec, yaml_p = _setup_fake_repo(tmp_path, spec_text=bad)
    rc, data = _run(repo, spec, yaml_p)
    assert rc == 0, data
    assert data["verdict"] == "WARN", data
    assert any(
        e["type"] == "codegen_page_evaluate_warning"
        for e in data["evidence"]
    )


def test_block_on_route_mismatch(tmp_path):
    repo, spec, yaml_p = _setup_fake_repo(tmp_path, spec_text=WELL_FORMED_SPEC)
    rc, data = _run(repo, spec, yaml_p, route="/admin/different")
    assert rc == 1, data
    assert data["verdict"] == "BLOCK", data
    assert any(
        e["type"] == "codegen_route_mismatch"
        for e in data["evidence"]
    )


def test_block_on_unsupported_assertion_dsl(tmp_path):
    bad = WELL_FORMED_SPEC.replace(
        "'rows[*].name.includes(param)'",
        "'rows[*].name.endsWith(param)'",
    )
    repo, spec, yaml_p = _setup_fake_repo(tmp_path, spec_text=bad)
    rc, data = _run(repo, spec, yaml_p)
    assert rc == 1, data
    assert data["verdict"] == "BLOCK", data
    assert any(
        e["type"] == "codegen_unsupported_assertion_dsl"
        for e in data["evidence"]
    )


def test_block_on_filename_mismatch(tmp_path):
    repo, spec, yaml_p = _setup_fake_repo(
        tmp_path,
        spec_text=WELL_FORMED_SPEC,
        spec_basename="wrong-name.spec.ts",
    )
    rc, data = _run(repo, spec, yaml_p)
    assert rc == 1, data
    assert data["verdict"] == "BLOCK", data
    assert any(
        e["type"] == "codegen_filename_mismatch"
        for e in data["evidence"]
    )
