#!/usr/bin/env python3
"""Verify/repair Graphify installation for VGFlow projects.

This is intentionally separate from /vg:build. Install/update should make the
tooling available; build owns graph freshness and emits events.db evidence.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from importlib import metadata
from pathlib import Path


PACKAGE = "graphifyy[mcp]"
GRAPHIFY_IMPORT = "graphify"


def _truthy(value: str | None) -> bool:
    return (value or "").strip().lower() in {"1", "true", "yes", "on"}


def _section_value(config: str, section: str, key: str, default: str = "") -> str:
    import re

    match = re.search(rf"^{re.escape(section)}:\s*$", config, re.MULTILINE)
    if not match:
        return default
    tail = config[match.end():]
    next_section = re.search(r"^[a-zA-Z_][\w-]*:\s*$", tail, re.MULTILINE)
    block = tail[: next_section.start()] if next_section else tail
    value = re.search(rf"^\s+{re.escape(key)}:\s*(.+?)\s*$", block, re.MULTILINE)
    if not value:
        return default
    return value.group(1).strip().strip("\"'")


def graphify_enabled(target: Path) -> bool:
    config = target / ".claude" / "vg.config.md"
    if not config.exists():
        return True
    text = config.read_text(encoding="utf-8", errors="replace")
    return _section_value(text, "graphify", "enabled", "true").lower() == "true"


def importable() -> bool:
    override = os.environ.get("VGFLOW_GRAPHIFY_ASSUME_IMPORTABLE")
    if override is not None:
        return _truthy(override)
    try:
        __import__(GRAPHIFY_IMPORT)
        return True
    except Exception:
        return False


def installed_version() -> str:
    for name in ("graphifyy", "graphify"):
        try:
            return metadata.version(name)
        except metadata.PackageNotFoundError:
            continue
    return "unknown"


def run(cmd: list[str], *, quiet: bool = False, cwd: Path | None = None) -> int:
    proc = subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if not quiet and proc.stdout:
        lines = proc.stdout.strip().splitlines()
        for line in lines[-6:]:
            print(f"  {line}")
    return proc.returncode


def ensure_graphifyignore(target: Path, *, repair: bool) -> bool:
    path = target / ".graphifyignore"
    if path.exists():
        return False
    if not repair:
        return True
    path.write_text(
        "\n".join([
            "# Auto-generated by VGFlow",
            ".planning/",
            ".claude/",
            ".codex/",
            ".vg/",
            "node_modules/",
            "dist/",
            "build/",
            "target/",
            ".next/",
            "graphify-out/",
            "test-results/",
            "playwright-report/",
            "coverage/",
            "ios/Pods/",
            "ios/build/",
            "android/.gradle/",
            "android/app/build/",
            ".dart_tool/",
            "",
        ]),
        encoding="utf-8",
    )
    return True


def ensure_gitignore(target: Path, *, repair: bool) -> bool:
    path = target / ".gitignore"
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8", errors="replace")
    if any(line.strip() == "graphify-out/" for line in text.splitlines()):
        return False
    if not repair:
        return True
    suffix = "\n# Graphify knowledge graph (regenerable)\ngraphify-out/\n"
    path.write_text(text.rstrip() + suffix, encoding="utf-8")
    return True


def ensure_mcp(target: Path, *, repair: bool) -> bool:
    path = target / ".mcp.json"
    if path.exists() and path.stat().st_size > 0:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            print(f"WARN: {path} is invalid JSON; refusing to overwrite.")
            return True
    else:
        data = {}

    data.setdefault("mcpServers", {})
    entry = {
        "command": "python",
        "args": ["-m", "graphify.serve", "graphify-out/graph.json"],
        "env": {},
        "type": "stdio",
    }
    if data["mcpServers"].get("graphify") == entry:
        return False
    if "graphify" in data["mcpServers"] and not repair:
        return False
    if not repair:
        return True
    data["mcpServers"]["graphify"] = entry
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return True


def install_graphify(*, quiet: bool, upgrade: bool) -> bool:
    cmd = [sys.executable, "-m", "pip", "install", "--user"]
    if upgrade:
        cmd.append("--upgrade")
    cmd.append(PACKAGE)
    if quiet:
        cmd.append("--quiet")
    print("Installing graphifyy[mcp]..." if not upgrade else "Updating graphifyy[mcp]...")
    return run(cmd, quiet=quiet) == 0 and importable()


def install_graphify_claude_hooks(*, quiet: bool) -> None:
    # Non-fatal: build/review use Python graph files; Claude MCP is a convenience.
    run([sys.executable, "-m", "graphify", "install", "--platform", "claude"], quiet=quiet)
    run([sys.executable, "-m", "graphify", "claude", "install"], quiet=quiet)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", default=".", help="Project root to repair.")
    parser.add_argument("--repair", action="store_true", help="Install/repair missing bits.")
    parser.add_argument("--quiet", action="store_true")
    parser.add_argument("--upgrade", action="store_true", help="Upgrade graphifyy if already installed.")
    args = parser.parse_args()

    target = Path(args.target).resolve()

    if _truthy(os.environ.get("VGFLOW_SKIP_GRAPHIFY_INSTALL")):
        if not args.quiet:
            print("Graphify: skipped by VGFLOW_SKIP_GRAPHIFY_INSTALL=true")
        return 0

    if not graphify_enabled(target):
        if not args.quiet:
            print("Graphify: skipped because graphify.enabled=false")
        return 0

    if sys.version_info < (3, 10):
        print("WARN: Python 3.10+ required for graphify; skipping install.")
        return 1

    changed = False
    has_graphify = importable()
    if not has_graphify:
        if not args.repair:
            print("Graphify: missing")
            return 1
        has_graphify = install_graphify(quiet=args.quiet, upgrade=False)
        changed = True
    elif args.upgrade or _truthy(os.environ.get("VGFLOW_GRAPHIFY_UPGRADE")):
        has_graphify = install_graphify(quiet=args.quiet, upgrade=True)
        changed = True

    if not has_graphify:
        print("WARN: graphify import still fails after install attempt.")
        return 1

    install_graphify_claude_hooks(quiet=args.quiet)
    changed = ensure_graphifyignore(target, repair=args.repair) or changed
    changed = ensure_gitignore(target, repair=args.repair) or changed
    changed = ensure_mcp(target, repair=args.repair) or changed

    if changed and not args.repair:
        if not args.quiet:
            print("Graphify: repair needed")
        return 1

    if not args.quiet:
        version = installed_version()
        state = "repaired" if changed else "ready"
        print(f"Graphify: {state} (package={version}, target={target})")
        print("Graphify graph build is handled by /vg:build or run manually: python -m graphify update .")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
