# shellcheck shell=bash
# inject-rule-cards.sh — emit compressed rule cards for a (skill, step) tuple
#
# Harness v2.6 (2026-04-25): Tầng 2 of memory-vs-enforce strategy.
# Cards generated by extract-rule-cards.py from skill files. This helper
# emits the relevant section at step start so AI sees a focused 5-30 line
# digest instead of skimming 1500-3000 line skill body.
#
# Why bash function (not pure Python):
#   Skill file `<step>` bodies invoke bash blocks. Adding a bash function
#   call is the lowest-friction way to wire cards into existing skill
#   structure. Function emits to stdout (so AI sees output in context)
#   and stderr (so logs capture it).
#
# Usage from skill:
#   <step name="0_parse_args">
#     `bash` block:
#       source .claude/commands/vg/_shared/lib/inject-rule-cards.sh
#       inject_rule_cards "vg-build" "0_parse_args"
#     ... rest of step ...
#   </step>
#
# CLI usage (operator manual review):
#   bash .claude/commands/vg/_shared/lib/inject-rule-cards.sh vg-build 0_parse_args
#
# Output shape:
#   ━━━ Rules for vg-build / 0_parse_args ━━━
#   [Top-level rules — apply to ALL steps]
#   - R1 [enforce] → validator-X: rule body...
#   ...
#   [Step-specific rules]
#   - [enforce] MUST: text  → validator-Y
#   - [remind] PHẢI: text
#   ...
#   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"

# Print rule cards for one step.
# $1 = skill name (e.g., "vg-build")
# $2 = step name (e.g., "0_parse_args")
# Optional flag: $3="quiet" suppresses output banner
inject_rule_cards() {
  local skill="$1"
  local step="$2"
  local mode="${3:-normal}"

  local cards_file="${REPO_ROOT}/.codex/skills/${skill}/RULES-CARDS.md"
  if [ ! -f "$cards_file" ]; then
    # Cards not generated yet — skill operator should run extract-rule-cards.py
    [ "$mode" = "quiet" ] || echo "▸ rule-cards not found for ${skill} (run: python3 .claude/scripts/validators/extract-rule-cards.py)" >&2
    return 0
  fi

  if [ "$mode" != "quiet" ]; then
    echo ""
    echo "━━━ Rules for ${skill} / ${step} ━━━"
  fi

  # Use awk to extract:
  #   1. Top-level rules section (between "## Top-level rules" and next "##")
  #   2. The step-specific section (between "### Step: \`<step>\`" and next "### Step:")
  #
  # Concatenate both with separator. Skip if section empty.
  awk -v step="### Step: \`${step}\`" '
    BEGIN { in_top=0; in_step=0; printed_top_header=0; printed_step_header=0 }

    /^## Top-level rules/ {
      in_top=1
      print "[Top-level rules — apply to ALL steps]"
      next
    }

    /^## Per-step rules/ {
      in_top=0
      next
    }

    in_top && /^### / { in_top=0 }
    in_top && /^---$/ { in_top=0 }

    in_top && (NF > 0) {
      # Skip blank lines, anti-pattern markers under top section, etc.
      print
      next
    }

    # Detect start of target step section
    $0 == step {
      in_step=1
      print ""
      print "[Step-specific rules: " step "]"
      next
    }

    in_step && /^### Step:/ { in_step=0 }
    in_step && /^---$/ { in_step=0 }
    in_step && /^## / { in_step=0 }

    in_step && (NF > 0) {
      print
      next
    }
  ' "$cards_file"

  # v2.6.4 (2026-04-26): also emit manual-curated rules from
  # RULES-CARDS-MANUAL.md if present. These persist across regeneration
  # of the auto file. Operator manages via edit-rule-cards.py CLI.
  local manual_file="${REPO_ROOT}/.codex/skills/${skill}/RULES-CARDS-MANUAL.md"
  if [ -f "$manual_file" ]; then
    # Only emit if file has actual rules (not just template placeholders)
    if grep -qE "^\s*-\s+\*\*(MANUAL|OVERRIDE|ANTI)-[0-9]+" "$manual_file" 2>/dev/null; then
      echo ""
      echo "[Manual rules — operator-curated, persisted across regen]"
      # Track section context + entry context — emit rule + body line
      # below it (1 indented continuation line per rule). Captures body
      # text without dragging in unrelated content from the section.
      awk -v step_h="### Step: \`${step}\`" -v step_anti_h="### Step: \`${step}\` — Anti-patterns" '
        BEGIN { in_top=0; in_step=0; in_over=0; in_entry=0; printed_section="" }
        function maybe_emit_section_header(name) {
          if (printed_section != name) {
            print "  [" name "]"
            printed_section = name
          }
        }
        # Detect section transitions (any header line ends current entry context)
        /^#{2,}/ {
          in_top = ($0 ~ /^## Top-level/)
          in_step = ($0 == step_h || $0 == step_anti_h)
          in_over = ($0 ~ /^## Overrides/)
          in_entry = 0
          next
        }
        # Inside a relevant section, emit rule entries + 1 body line below
        (in_top || in_step || in_over) && /^- \*\*(MANUAL|OVERRIDE|ANTI)-[0-9]+/ {
          if (in_top) maybe_emit_section_header("Top-level")
          else if (in_step && $0 ~ /ANTI-/) maybe_emit_section_header(step_anti_h)
          else if (in_step) maybe_emit_section_header(step_h)
          else if (in_over) maybe_emit_section_header("Overrides")
          print "    " $0
          in_entry = 1
          next
        }
        # Continuation line directly below an entry (body text, indented)
        in_entry && /^\s{2,}/ {
          print "    " $0
          next
        }
        # Blank or new entry boundary
        /^$/ || /^- / { in_entry = 0 }
      ' "$manual_file"
    fi
  fi

  if [ "$mode" != "quiet" ]; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
  fi
}

# Convenience: print just the step section (no top-level rules).
inject_rule_cards_step_only() {
  local skill="$1"
  local step="$2"
  local cards_file="${REPO_ROOT}/.codex/skills/${skill}/RULES-CARDS.md"
  [ -f "$cards_file" ] || return 0

  awk -v step="### Step: \`${step}\`" '
    $0 == step { in_step=1; print; next }
    in_step && /^### Step:/ { exit }
    in_step && /^---$/ { exit }
    in_step && /^## / { exit }
    in_step { print }
  ' "$cards_file"
}

# CLI entry point — when invoked directly (not sourced)
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  if [ "$#" -lt 2 ]; then
    echo "Usage: $0 <skill> <step> [quiet]" >&2
    echo "Example: $0 vg-build 0_parse_args" >&2
    exit 1
  fi
  inject_rule_cards "$@"
fi
