# shellcheck shell=bash
# Planning Migrator — migrate .planning/ → .vg/ (v1.12.0 R7)
#
# Purpose: VG workflow uses .vg/ as canonical. GSD legacy uses .planning/.
# Migrator scans .planning/ comprehensively, classifies each file as VG-owned
# vs GSD-owned, copies VG-owned to .vg/ following VG file convention strictly.
#
# Idempotent: safe to re-run. Compares hashes, only copies if differ.
# Re-running pulls latest from .planning/ → updates .vg/ (preserves user edits
# in .vg-only files via .pre-migrate backup).
#
# Comprehensive: walks ALL files in .planning/, doesn't skip silently.
# Reports: NEW / UPDATED / UNCHANGED / SKIPPED-GSD / BACKED-UP per file.
#
# Exposed functions:
#   planning_migrator_run [--dry-run] [--keep-original]
#   planning_migrator_classify FILE_PATH       # → vg|gsd|shared|unknown
#   planning_migrator_is_gsd_only FILE_PATH    # returns 0 if GSD-owned
#   planning_migrator_report                   # post-run summary
#
# GSD ownership signals:
#   - File contains "## GSD" / "Generated by gsd-" / "[GSD]" markers
#   - File path matches: */gsd-*/* | */RESEARCH.md (GSD style) | *.gsd
#   - Phase dir has GSD-specific structure: gsd-state.json, etc.
#
# VG ownership signals (default):
#   - Standard VG artifacts: PROJECT.md, FOUNDATION.md, ROADMAP.md, STATE.md
#   - phases/XX/{SPECS,CONTEXT,PLAN,API-CONTRACTS,TEST-GOALS,SUMMARY}.md
#   - design/, intel/, telemetry.jsonl, overrides.jsonl, vg-eval/
#   - File contains "P{phase}.D-XX" namespace OR vg-specific markers

PM_DEFAULT_SOURCE=".planning"
PM_DEFAULT_TARGET=".vg"

# Counters (set in planning_migrator_run)
PM_STATS_NEW=0
PM_STATS_UPDATED=0
PM_STATS_UNCHANGED=0
PM_STATS_SKIPPED_GSD=0
PM_STATS_BACKED_UP=0
PM_STATS_TOTAL=0

# Classify file as vg-owned, gsd-owned, shared (both), or unknown.
# stdout: "vg" | "gsd" | "shared" | "unknown"
planning_migrator_classify() {
  local file="$1"
  [ -f "$file" ] || { echo "unknown"; return 1; }

  local rel="${file#$PM_SOURCE/}"

  # Path-based GSD signals (high confidence)
  case "$rel" in
    *.gsd|*.gsd-*|gsd-*|*/gsd-*/*|gsd-state.json)
      echo "gsd"; return 0 ;;
    debug/*|quick/*|research/*)
      # GSD has these subdirs, VG doesn't
      echo "gsd"; return 0 ;;
    codebase/*)
      # GSD codebase intel folder. VG uses codebase-map.md (single file)
      echo "gsd"; return 0 ;;
    *.gitkeep)
      echo "shared"; return 0 ;;
  esac

  # Path-based VG signals (high confidence)
  case "$rel" in
    PROJECT.md|FOUNDATION.md|ROADMAP.md|STATE.md|codebase-map.md)
      echo "vg"; return 0 ;;
    telemetry.jsonl|overrides.jsonl)
      echo "vg"; return 0 ;;
    design/*|design/**)
      echo "vg"; return 0 ;;
    intel/*|intel/**)
      echo "vg"; return 0 ;;
    vg-eval/*|vg-eval/**|vgflow-patches/*|vgflow-patches/**|vgflow-ancestor/*|vgflow-ancestor/**)
      echo "vg"; return 0 ;;
    config.json|brief.md|REQUIREMENTS.md|TEST-REPORT-VI.md|TEST-STRATEGY.md|REMOVED-*.md)
      # GSD legacy artifacts at top-level (heuristic). Skip.
      echo "gsd"; return 0 ;;
  esac

  # Phase folder content classification
  case "$rel" in
    phases/*)
      local phase_file
      phase_file=$(echo "$rel" | sed -E 's|phases/[^/]+/||')
      case "$phase_file" in
        SPECS.md|CONTEXT.md|PLAN.md|API-CONTRACTS.md|TEST-GOALS.md|SUMMARY*.md|RUNTIME-MAP.json|GOAL-COVERAGE-MATRIX.md|PIPELINE-STATE.json|DISCUSSION-LOG.md|UAT.md|SANDBOX-TEST.md|AMENDMENT-LOG.md|REVIEW.md|VERIFICATION.md|SECURITY.md|UI-SPEC.md|UI-REVIEW.md|FLOW-*.md|RESEARCH.md|.step-markers/*)
          # All standard VG phase artifacts
          echo "vg"; return 0 ;;
        crossai/*|checkpoints/*|element-counts.json|view-assignments*.json|nav-discovery.json|scan-*.json|.surface-probe-results.json|.bug-reports*|07.*-PLAN.md|07.*-SUMMARY.md|*.spec.ts|TEST-RESULTS.md)
          # VG sub-artifacts (browser scans, plans by gsd that VG inherits, etc.)
          echo "vg"; return 0 ;;
        gsd-*|*.gsd|RESULT.md)
          # GSD-only phase artifacts
          echo "gsd"; return 0 ;;
        *)
          # Unknown phase file — classify by content signals
          ;;
      esac
      ;;
  esac

  # Content-based classification (fallback)
  if grep -qE "^## GSD\b|Generated by gsd-|^\[GSD\]" "$file" 2>/dev/null; then
    echo "gsd"; return 0
  fi

  if grep -qE "P[0-9.]+\.D-[0-9]+|D-[0-9]+:.*VG-native|/vg:|vg-config\.md" "$file" 2>/dev/null; then
    echo "vg"; return 0
  fi

  # Default: classify by extension
  case "$file" in
    *.md|*.json|*.jsonl|*.txt|*.tsv) echo "vg"; return 0 ;;
    *.done|*.err) echo "shared"; return 0 ;;
    *.sh) echo "shared"; return 0 ;;
    *.xml) echo "vg"; return 0 ;;
  esac

  echo "unknown"
}

# Returns 0 if file is GSD-owned (skip during VG migrate)
planning_migrator_is_gsd_only() {
  local file="$1"
  local class
  class=$(planning_migrator_classify "$file")
  [ "$class" = "gsd" ]
}

# Compute file hash (sha256 first 16 chars for speed)
planning_migrator_hash() {
  local file="$1"
  [ -f "$file" ] || { echo ""; return 1; }
  ${PYTHON_BIN:-python3} -c "
import hashlib, sys
with open('$file', 'rb') as f:
    print(hashlib.sha256(f.read()).hexdigest()[:16])
" 2>/dev/null
}

# Detect if target file has been edited AFTER initial migration
# Heuristic: compare against .pre-migrate backup if exists
planning_migrator_is_user_edited() {
  local target="$1"
  local backup="${target}.pre-migrate"
  [ -f "$backup" ] || return 1  # no backup = no prior migration
  [ "$(planning_migrator_hash "$target")" != "$(planning_migrator_hash "$backup")" ]
}

# Migrate single file: source → target
# Returns: 0 if successful, status echoed to stdout
planning_migrator_migrate_file() {
  local src="$1"
  local rel="${src#$PM_SOURCE/}"
  local dst="$PM_TARGET/$rel"

  PM_STATS_TOTAL=$((PM_STATS_TOTAL + 1))

  local class
  class=$(planning_migrator_classify "$src")

  if [ "$class" = "gsd" ]; then
    echo "  SKIP-GSD:    $rel"
    PM_STATS_SKIPPED_GSD=$((PM_STATS_SKIPPED_GSD + 1))
    return 0
  fi

  # Ensure target dir exists
  if [ "${PM_DRY_RUN:-false}" != "true" ]; then
    mkdir -p "$(dirname "$dst")" 2>/dev/null || true
  fi

  if [ ! -f "$dst" ]; then
    if [ "${PM_DRY_RUN:-false}" = "true" ]; then
      echo "  WOULD-NEW:   $rel"
    else
      cp -p "$src" "$dst"
      echo "  NEW:         $rel"
    fi
    PM_STATS_NEW=$((PM_STATS_NEW + 1))
    return 0
  fi

  # Compare hashes
  local src_hash dst_hash
  src_hash=$(planning_migrator_hash "$src")
  dst_hash=$(planning_migrator_hash "$dst")

  if [ "$src_hash" = "$dst_hash" ]; then
    PM_STATS_UNCHANGED=$((PM_STATS_UNCHANGED + 1))
    return 0
  fi

  # Differ — check if user edited target
  if planning_migrator_is_user_edited "$dst"; then
    if [ "${PM_DRY_RUN:-false}" = "true" ]; then
      echo "  WOULD-UPDATE-WITH-BACKUP: $rel"
    else
      cp -p "$dst" "${dst}.user-edit.$(date +%s)"
      cp -p "$src" "$dst"
      echo "  UPDATED-BACKED-UP: $rel"
    fi
    PM_STATS_BACKED_UP=$((PM_STATS_BACKED_UP + 1))
  else
    if [ "${PM_DRY_RUN:-false}" = "true" ]; then
      echo "  WOULD-UPDATE: $rel"
    else
      # Save .pre-migrate baseline for future user-edit detection
      [ ! -f "${dst}.pre-migrate" ] && cp -p "$dst" "${dst}.pre-migrate"
      cp -p "$src" "$dst"
      echo "  UPDATED:     $rel"
    fi
    PM_STATS_UPDATED=$((PM_STATS_UPDATED + 1))
  fi
}

# Main migration runner
# Args: --dry-run (preview only) | --keep-original (don't delete .planning after)
planning_migrator_run() {
  local dry_run=false
  local keep_original=true  # default safe: don't auto-delete

  for arg in "$@"; do
    case "$arg" in
      --dry-run)        dry_run=true ;;
      --no-keep)        keep_original=false ;;
      --source=*)       PM_SOURCE="${arg#*=}" ;;
      --target=*)       PM_TARGET="${arg#*=}" ;;
    esac
  done

  PM_SOURCE="${PM_SOURCE:-$PM_DEFAULT_SOURCE}"
  PM_TARGET="${PM_TARGET:-$PM_DEFAULT_TARGET}"
  export PM_DRY_RUN="$dry_run"

  # Reset stats
  PM_STATS_NEW=0
  PM_STATS_UPDATED=0
  PM_STATS_UNCHANGED=0
  PM_STATS_SKIPPED_GSD=0
  PM_STATS_BACKED_UP=0
  PM_STATS_TOTAL=0

  if [ ! -d "$PM_SOURCE" ]; then
    echo "⛔ Source $PM_SOURCE doesn't exist. Nothing to migrate."
    return 1
  fi

  echo "═══════════════════════════════════════════════════════════════"
  echo "  Planning Migrator: $PM_SOURCE → $PM_TARGET"
  if [ "$dry_run" = "true" ]; then
    echo "  Mode: DRY-RUN (no files written)"
  else
    echo "  Mode: APPLY"
  fi
  echo "═══════════════════════════════════════════════════════════════"
  echo ""

  if [ "$dry_run" != "true" ]; then
    mkdir -p "$PM_TARGET"
  fi

  # Walk all files in source, migrate each
  while IFS= read -r src; do
    [ -f "$src" ] || continue
    planning_migrator_migrate_file "$src"
  done < <(find "$PM_SOURCE" -type f 2>/dev/null | sort)

  echo ""
  planning_migrator_report

  if [ "$dry_run" != "true" ] && [ "$keep_original" = "false" ] && [ "$PM_STATS_BACKED_UP" -eq 0 ]; then
    echo ""
    echo "⚠ --no-keep flag set + zero backup conflicts. Source $PM_SOURCE will be removed."
    echo "  Press Ctrl+C in 5s to abort..."
    sleep 5
    rm -rf "$PM_SOURCE"
    echo "✓ $PM_SOURCE removed."
  fi
}

planning_migrator_report() {
  echo "═══════════════════════════════════════════════════════════════"
  echo "  Migration Summary"
  echo "═══════════════════════════════════════════════════════════════"
  echo "  Total scanned:     $PM_STATS_TOTAL"
  echo "  ✓ NEW:             $PM_STATS_NEW (didn't exist in target)"
  echo "  ↻ UPDATED:         $PM_STATS_UPDATED (source newer)"
  echo "  ⚠ BACKED-UP:       $PM_STATS_BACKED_UP (target had user edits, .user-edit.* saved)"
  echo "  · UNCHANGED:       $PM_STATS_UNCHANGED (already in sync)"
  echo "  ✗ SKIPPED-GSD:     $PM_STATS_SKIPPED_GSD (GSD-owned, not migrated)"
  echo ""
  if [ "$PM_STATS_BACKED_UP" -gt 0 ]; then
    echo "⚠ ${PM_STATS_BACKED_UP} files had user edits. Backups at *.user-edit.<ts>"
    echo "  Review + merge manually if needed."
  fi
}
