#!/usr/bin/env python3
"""write-pre-test-report.py — render PRE-TEST-REPORT.md from JSON inputs."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def _row(name: str, result: dict) -> str:
    status = result.get("status", "UNKNOWN")
    glyph = {"PASS": "✓", "BLOCK": "⛔", "SKIPPED": "—", "UNKNOWN": "?"}.get(status, "?")
    duration = result.get("duration_ms", 0)
    detail = result.get("reason") or result.get("runner") or ""
    return f"| {name} | {glyph} {status} | {duration}ms | {detail} |"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--phase", required=True)
    parser.add_argument("--t12-report", required=True)
    parser.add_argument("--deploy-report")
    parser.add_argument("--no-deploy", action="store_true")
    parser.add_argument("--t3-note", default="")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    t12 = json.loads(Path(args.t12_report).read_text(encoding="utf-8"))

    out = []
    out.append(f"# Pre-Test Report — {args.phase}")
    out.append("")
    out.append(f"**Started:** {t12.get('started_at', '?')}")
    out.append(f"**Completed:** {t12.get('completed_at', '?')}")
    out.append("")
    out.append("## Tier 1 — Static checks")
    out.append("")
    out.append("| Check | Status | Duration | Detail |")
    out.append("|---|---|---|---|")
    for k, v in t12.get("tier_1", {}).items():
        out.append(_row(k, v))
        if k == "debug_leftover" and v.get("evidence"):
            for ev in v["evidence"][:5]:
                out.append(f"  - `{ev.get('file')}:{ev.get('line')}` — `{ev.get('label')}`: `{ev.get('snippet', '')}`")
    out.append("")
    out.append("## Tier 2 — Local tests")
    out.append("")
    t2 = t12.get("tier_2", {})
    out.append("| Status | Runner | Duration | Detail |")
    out.append("|---|---|---|---|")
    glyph = {"PASS": "✓", "BLOCK": "⛔", "SKIPPED": "—"}.get(t2.get("status"), "?")
    out.append(f"| {glyph} {t2.get('status', '?')} | {t2.get('runner', '–')} | {t2.get('duration_ms', 0)}ms | {t2.get('reason', '')} |")
    out.append("")
    if args.t3_note:
        out.append("## Tier 3 — Local smoke (informational)")
        out.append("")
        out.append(args.t3_note)
        out.append("")
    out.append("## Deploy + post-deploy smoke")
    out.append("")
    if args.no_deploy:
        out.append("Deploy: SKIPPED (user opted not to deploy or profile = library/cli-tool).")
    elif args.deploy_report:
        d = json.loads(Path(args.deploy_report).read_text(encoding="utf-8"))
        out.append(f"**Decision:** {d.get('decision', '?')}")
        out.append(f"**Deployed:** {'yes' if d.get('deployed') else 'no'}")
        if d.get("deploy_url"):
            out.append(f"**URL:** {d['deploy_url']}")
        if d.get("smoke_health_check"):
            hc = d["smoke_health_check"]
            out.append(f"**Health check:** {hc.get('status')} ({hc.get('code')} on {hc.get('endpoint')}, {hc.get('attempts', 1)} attempts)")
        if d.get("smoke_test_run"):
            sr = d["smoke_test_run"]
            out.append(f"**Smoke specs:** {sr.get('status')} ({sr.get('spec_count', 0)} specs, {sr.get('duration_ms', 0)}ms)")
    out.append("")
    out.append("---")
    out.append("Generated by `scripts/validators/write-pre-test-report.py`.")

    Path(args.output).write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"✓ Wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
